id = "rainbow-icons"
name = "Rainbow Icons Theme"
version = "0.1.0"
schema_version = 1
authors = ["Athan Xiao <athanseal@gmail.com>"]
description = "Rainbow icons theme for Zed"
repository = "https://github.com/athxx/zed-icons-rainbow"
